export const loremIpsum = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla luctus eros in lectus feugiat, ut congue felis ullamcorper. Sed diam enim, commodo quis ultricies eleifend, euismod vitae risus. Nulla non vestibulum metus. Pellentesque placerat rutrum turpis ac mollis. Sed est ante, condimentum eu fermentum quis, suscipit sit amet ligula. Nullam risus justo, tincidunt vel sem ac, vulputate molestie tortor. Suspendisse dui risus, venenatis et hendrerit ac, pharetra eu nunc. Sed ultricies eleifend lectus vitae hendrerit. Pellentesque non pellentesque dolor. Donec ac purus mattis, aliquet nisi id, maximus velit. Curabitur arcu sapien, suscipit nec lorem eu, consequat congue orci. Donec egestas nec nunc id placerat. Donec non laoreet arcu, non lobortis orci. Maecenas vel dapibus odio. Proin eu odio sem. Fusce porta rutrum ipsum quis venenatis.\n' +
  '\n' +
  'Integer ac diam vel justo euismod aliquet quis eget nisi. Mauris maximus pulvinar malesuada. Nulla facilisi. In sollicitudin malesuada eleifend. Nam iaculis elementum ex, sed gravida mauris dapibus vel. Mauris sed massa in nibh ornare ullamcorper non et odio. Duis porttitor tempus velit, nec facilisis libero imperdiet et. Donec scelerisque, felis nec pellentesque hendrerit, nulla nisi iaculis dolor, ac ullamcorper libero mi sed purus. Mauris metus leo, euismod id molestie quis, convallis suscipit ante. Suspendisse eu neque ut turpis porttitor condimentum in quis arcu.\n' +
  '\n' +
  'Phasellus laoreet tempor diam, in iaculis massa elementum quis. Integer vehicula neque quis nibh molestie tempor. Morbi hendrerit velit a porta feugiat. Quisque non eros ut neque varius elementum non at ex. Pellentesque vestibulum nunc ac gravida accumsan. Nulla id ipsum at libero aliquet ullamcorper nec et massa. Cras congue finibus risus a porttitor.\n' +
  '\n' +
  'Sed massa ligula, lacinia non libero non, condimentum commodo turpis. Etiam cursus turpis vel turpis consequat accumsan. Fusce nunc mauris, ultricies nec egestas vitae, interdum at felis. Quisque massa quam, consectetur ac turpis in, vehicula lacinia tortor. Etiam accumsan arcu nulla, ac semper tortor commodo ac. Nunc tempor nisl id molestie ultricies. Nullam vehicula libero sodales metus lobortis sollicitudin.\n' +
  '\n' +
  'Etiam commodo sapien mi, ultricies egestas felis tincidunt eu. Nullam vitae mi et tellus dignissim eleifend. Nullam aliquam, sapien sed blandit venenatis, dui lorem vulputate felis, a porta massa purus sodales dui. Nunc commodo lacinia diam, quis dapibus mauris vehicula ut. Integer porttitor, urna at consectetur vehicula, justo nulla euismod leo, egestas porttitor lorem lacus vel dui. Donec feugiat sollicitudin leo quis facilisis. Pellentesque vel ultrices metus. Donec et condimentum odio. In porta, lectus facilisis auctor iaculis, sem odio consequat urna, eget tincidunt mauris diam molestie lorem. In viverra justo vel justo pharetra placerat. Donec tincidunt libero ante, id consectetur arcu pulvinar sed. Curabitur eget augue imperdiet lectus viverra luctus ut in quam. Cras eget lacus non odio gravida feugiat ut nec odio. Integer vel volutpat magna, quis consequat magna. Proin non malesuada enim, eget porttitor risus.'
